name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test insertion
      id: test-insertion
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test insertion
        setup-command: pip install pytest
        command: " python -m pytest tests/test_insertion.py -v"
        timeout: 10
        max-score: 30
    - name: Test insertion
      id: test-insertion
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test insertion
        setup-command: pip install pytest
        command: " python -m pytest tests/test_insertion.py -v"
        timeout: 30
    - name: Test selection
      id: test-selection
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test selection
        setup-command: pip install pytest
        command: python -m pytest tests/test_selection.py -v
        timeout: 10
        max-score: 30
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-INSERTION_RESULTS: "${{steps.test-insertion.outputs.result}}"
        TEST-SELECTION_RESULTS: "${{steps.test-selection.outputs.result}}"
      with:
        runners: test-insertion,test-insertion,test-selection
